# Generated by Django 5.2.2 on 2025-10-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('welcome', 'Powitanie'), ('moderation', 'Moderacja'), ('review', 'Opinia'), ('system', 'Systemowe')], default='system', max_length=20),
        ),
    ]
