# Generated by Django 5.2.2 on 2025-11-09 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_link_url_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Moderator, który utworzył powiadomienie ręcznie.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_staff_message',
            field=models.BooleanField(default=False, help_text='Czy to powiadomienie zostało utworzone ręcznie przez moderatora?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('welcome', 'Powitanie'), ('moderation', 'Moderacja'), ('review', 'Opinia'), ('system', 'Systemowe'), ('staff_message', 'Wiadomość od moderatora')], default='system', max_length=20),
        ),
    ]
