# Generated by Django 5.2.2 on 2025-06-17 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_type', models.CharField(choices=[('private', 'Prywatne'), ('business', 'Firmowe')], max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('listing_type', models.CharField(choices=[('sale', 'Sprzedaż'), ('exchange', 'Wymiana'), ('both', 'Sprzedaż i wymiana')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('opening_hours', models.CharField(blank=True, max_length=100)),
                ('invoice_option', models.BooleanField(default=False)),
                ('nip', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
