# Generated by Django 5.2.2 on 2025-06-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='listing_type',
            field=models.CharField(choices=[('sale_or_exchange', 'Sprzedaż / Wymiana'), ('free', 'Oddam za darmo')], max_length=22),
        ),
    ]
