# Generated by Django 5.2.2 on 2025-06-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcementimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='invoice_option',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='nip',
        ),
        migrations.AddField(
            model_name='announcement',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
