# Generated by Django 5.2.2 on 2025-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_remove_announcement_invoice_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('active', 'Aktywne'), ('paused', 'Zawieszone'), ('archived', 'Zarchiwizowane')], default='active', max_length=20),
        ),
    ]
