# Generated by Django 5.2.2 on 2025-09-28 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_alter_announcement_description_announcementlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
                ('handled_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='moderation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Oczekuje na weryfikację'), ('approved', 'Zatwierdzone przez moderację'), ('rejected', 'Odrzucone przez moderację')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['moderation_status'], name='announcemen_moderat_8a1a79_idx'),
        ),
        migrations.AddField(
            model_name='announcementreport',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='announcementreport',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_handled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcementreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
