# Generated by Django 5.2.2 on 2025-09-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_announcementreport_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnouncementReport',
        ),
    ]
