# Generated by Django 5.2.2 on 2025-10-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_delete_announcementreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptCheckedAnnouncement',
            fields=[
            ],
            options={
                'verbose_name': 'Sprawdzone przez MilfCheckera',
                'verbose_name_plural': 'Sprawdzone przez MilfCheckera',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('announcements.announcement',),
        ),
        migrations.AddField(
            model_name='announcement',
            name='editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Oczekuje na weryfikację'), ('approved', 'Zatwierdzone przez moderację'), ('rejected', 'Odrzucone przez moderację'), ('rejected_spam', 'Odrzucone jako spam'), ('script_check_approved', 'Automatycznie zatwierdzone przez MilfCheckera'), ('script_check_rejected', 'Odrzucone automatycznie przez MilfCheckera')], db_index=True, default='pending', max_length=25),
        ),
    ]
