# Generated by Django 5.2.2 on 2025-10-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_scriptcheckedannouncement_announcement_editable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Oczekuje na weryfikację'), ('script_check_approved', 'Automatycznie zatwierdzone przez MilfCheckera'), ('approved', 'Zatwierdzone przez moderację'), ('rejected', 'Odrzucone przez moderację'), ('needs_fix', 'Wymaga poprawy przez użytkownika'), ('rejected_spam', 'Zablokowane / Spam')], db_index=True, default='pending', max_length=25),
        ),
    ]
