# Generated by Django 5.2.2 on 2025-10-26 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0010_alter_announcement_moderation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='submission_source',
            field=models.CharField(choices=[('new', 'Nowe ogłoszenie'), ('edited', 'Edycja po publikacji'), ('resubmitted', 'Poprawione po odrzuceniu')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Oczekujące'), ('script_check_approved', 'Automatycznie zatwierdzone przez MilfCheckera'), ('script_check_rejected', 'Odrzucone przez skrypt'), ('approved', 'Zatwierdzone przez moderatora'), ('rejected', 'Odrzucone przez moderatora'), ('needs_fix', 'Do poprawy przez użytkownika'), ('rejected_spam', 'Zablokowane / Spam')], db_index=True, default='pending', max_length=25),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['submission_source'], name='announcemen_submiss_dcc41f_idx'),
        ),
    ]
