# Generated by Django 5.2.2 on 2025-10-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0011_announcement_submission_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementEdited',
            fields=[
            ],
            options={
                'verbose_name': 'Edytowane przez użytkowników',
                'verbose_name_plural': 'Edytowane przez użytkowników',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('announcements.announcement',),
        ),
        migrations.CreateModel(
            name='AnnouncementNew',
            fields=[
            ],
            options={
                'verbose_name': 'Nowe ogłoszenie',
                'verbose_name_plural': 'Nowe ogłoszenia',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('announcements.announcement',),
        ),
        migrations.CreateModel(
            name='AnnouncementResubmitted',
            fields=[
            ],
            options={
                'verbose_name': 'Poprawione przez użytkowników',
                'verbose_name_plural': 'Poprawione przez użytkowników',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('announcements.announcement',),
        ),
    ]
