# Generated by Django 5.2.2 on 2025-11-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0012_announcementedited_announcementnew_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnouncementEdited',
        ),
        migrations.DeleteModel(
            name='AnnouncementNew',
        ),
        migrations.DeleteModel(
            name='AnnouncementResubmitted',
        ),
        migrations.DeleteModel(
            name='ScriptCheckedAnnouncement',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='submission_source',
            field=models.CharField(choices=[('new', 'Dodane'), ('edited', 'Edytowane przez użytkownika'), ('resubmitted', 'Poprawione po sprawdzeniu')], db_index=True, default='new', max_length=20),
        ),
    ]
