# Generated by Django 5.2.2 on 2026-03-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0013_delete_announcementedited_delete_announcementnew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
