# Generated by Django 5.2.2 on 2026-03-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polish_cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polishcity',
            name='feature_code',
            field=models.CharField(default='PPL', max_length=10),
        ),
    ]
