# Generated by Django 5.2.2 on 2026-03-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polish_cities', '0002_polishcity_feature_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='polishcity',
            name='population',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
