# Generated by Django 5.2.2 on 2026-03-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polish_cities', '0003_polishcity_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='polishcity',
            name='admin1',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
