# Generated by Django 5.2.2 on 2026-03-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polish_cities', '0004_polishcity_admin1'),
    ]

    operations = [
        migrations.AddField(
            model_name='polishcity',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
