# Generated by Django 5.2.2 on 2025-11-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_register_resend',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='resend_register_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
