# Generated by Django 5.2.2 on 2025-12-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_last_register_resend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
