# Generated by Django 5.2.2 on 2025-12-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
