# Generated by Django 5.2.2 on 2025-11-15 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0013_delete_announcementedited_delete_announcementnew_and_more'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementChecked',
            fields=[
            ],
            options={
                'verbose_name': 'Nowe (sprawdzone przez MilfCheckera)',
                'verbose_name_plural': 'Nowe (sprawdzone przez MilfCheckera)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('announcements.announcement',),
        ),
        migrations.CreateModel(
            name='AnnouncementNeedsFix',
            fields=[
            ],
            options={
                'verbose_name': 'Do poprawy',
                'verbose_name_plural': 'Do poprawy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('announcements.announcement',),
        ),
        migrations.CreateModel(
            name='AnnouncementPendingEdit',
            fields=[
            ],
            options={
                'verbose_name': 'Oczekujące po edycji',
                'verbose_name_plural': 'Oczekujące po edycji',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('announcements.announcement',),
        ),
        migrations.CreateModel(
            name='AnnouncementRejected',
            fields=[
            ],
            options={
                'verbose_name': 'Odrzucone przez moderatora',
                'verbose_name_plural': 'Odrzucone przez moderatora',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('announcements.announcement',),
        ),
        migrations.CreateModel(
            name='AnnouncementResubmitted',
            fields=[
            ],
            options={
                'verbose_name': 'Poprawione po odrzuceniu',
                'verbose_name_plural': 'Poprawione po odrzuceniu',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('announcements.announcement',),
        ),
        migrations.CreateModel(
            name='AnnouncementSpam',
            fields=[
            ],
            options={
                'verbose_name': 'Spam / zablokowane',
                'verbose_name_plural': 'Spam / zablokowane',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('announcements.announcement',),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('announcement', 'Ogłoszenie'), ('review', 'Opinia'), ('user', 'Użytkownik')], max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('reason', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
                ('handled_reason', models.TextField(blank=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_handled', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zgłoszenie',
                'verbose_name_plural': 'Zgłoszenia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AnnouncementReport',
        ),
    ]
