# Generated by Django 5.2.2 on 2025-11-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_announcementchecked_announcementneedsfix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='handled',
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('new', 'Nowe'), ('in_review', 'W trakcie'), ('resolved', 'Zakończone')], db_index=True, default='new', max_length=20),
        ),
    ]
