# Generated by Django 5.2.2 on 2025-11-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_remove_report_handled_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('spam', 'Spam / reklama'), ('offensive', 'Obraźliwa treść'), ('rules_violation', 'Naruszenie regulaminu'), ('inappropriate', 'Nieodpowiednie zachowanie'), ('other', 'Inny powód')], db_index=True, default='other', max_length=30),
        ),
    ]
