# Generated by Django 5.2.2 on 2025-11-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_report_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('spam', 'Spam / Advertising'), ('offensive', 'Offensive content'), ('rules_violation', 'Rules violation'), ('inappropriate', 'Inappropriate behaviour'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('resolved', 'Resolved')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('review', 'Review'), ('user', 'User')], max_length=20),
        ),
    ]
